// <auto-generated />
namespace KidCloudProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddailyreportsmodelanddailyreportslisttodaycare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddailyreportsmodelanddailyreportslisttodaycare));
        
        string IMigrationMetadata.Id
        {
            get { return "201705092052162_added dailyreports model and dailyreports list to daycare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
