// <auto-generated />
namespace KidCloudProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedEventMVC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedEventMVC));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151550078_added Event MVC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
